### PR TITLE
Upgraded issue templates to use GitHub issue forms

### PR DESCRIPTION
**Pull request by vendz**
a pull request for #2

### CODE REVIEW

**Comment by lohanidamodar** [comment]
@vendz  Great work. One more change before we can approve. We have made few changes in the language and also the format of Code of conduct. Please check https://github.com/appwrite/appwrite template and update accordingly.
Thank you.

**Comment by vendz** [comment]
@lohanidamodar requested changes have been made. 
kindly review it!

**Review by lohanidamodar — APPROVED** [review]
@vendz great work 🚀

**Comment by christyjacob4** [comment]
THANK YOU so much! All changes merged 🥳
Please reach out to me on our [Discord server](https://appwrite.io/discord) if you would like to claim your Appwrite swag!

**Pull request merged**
